### ISSUE TITLE
Visualizations?

### ISSUE THREAD

**Issue by thorbjorn444** [alex/nyt-2020-election-scraper#105]
Would y'all have any interest in me adding some visualization capabilities? Something like this? 

https://colab.research.google.com/drive/19NmdUU-twMK83XbK5GwzYJ1NK2kYCEAI?usp=sharing

Sorry if this doesn't align with "issues", i'm new to contributing to OSS

**Comment by sebsebmc** [comment]
This started off as being all-text only and is still available in all text form here: https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.txt

I dont think we are going to be adding any visualization here but others are doing so in their own repos like https://saleemrashid.github.io/nyt-2020-election-scraper/
(Though he rewrote the whole thing in Go)

**Comment by wobsoriano** [comment]
Updated my simple viz using this data

https://election2020.vercel.app/

https://github.com/wobsoriano/election2020
