### ISSUE TITLE
Pennsylvania is not computing correctly

### ISSUE THREAD

**Issue by micheleboc** [alex/nyt-2020-election-scraper#106]
Please look at percentages and the vote count on Pennsylvania.

**Comment by sebsebmc** [comment]
Can you be more specific?
331,430\*0.5737 = 190,141
331,430\*(1-0.5737) = 141,289 + Lead of 48854 = 190,143
(there is some loss in precision due to rounding of 2 and 3 decimal places)
So this the vote count, remaining and hurdle seem correct to me

**Comment by micheleboc** [comment]
The block break down, says Biden is getting 72% but the total only went down by 1,817 out of 4035 votes. Is this including other candidates that are not showing up?

**Comment by sebsebmc** [comment]
Trump lead went down by 1817 votes, so Biden got 1817 more votes than Trump. 2926 to 1109 and 2926/4035 = 0.725 or 72.5%

**Comment by frewsxcv** [comment]
thanks for the report @micheleboc and thanks for digging into this @sebsebmc  ❤️

**Comment by micheleboc** [comment]
Oh! Thank you for explaining that. Please close or delete this.
