### ISSUE TITLE
Notifications aren't entirely accurate

### ISSUE THREAD

**Issue by connorshea** [alex/nyt-2020-election-scraper#109]
As I said [in this comment](https://github.com/alex/nyt-2020-election-scraper/pull/81#pullrequestreview-524815062), the current logic for notifications is imperfect in that they trigger when the site deploys with a change to the HTML rather than a change to the underlying data.

I'm not really sure how we could distinguish the two, honestly. We could hack around it by creating a separate file to track just the data that'd be updated every time the data updates (and then check for updates to that file rather than the generated HTML), or change the commit message when it is/isn't a data update.

**Comment by sebsebmc** [comment]
We are aware and the author of the notification code is working on it!

**Comment by NickHeiner** [comment]
Awesome! If possible, it would be great if it were easier to tell which data was new.

**Comment by sebsebmc** [comment]
If you so choose, you can look at the text file for lines with `***` those are less than 30 minutes old. 
https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.txt

I haven't seen any work on making that show up in the HTML yet
