### ISSUE TITLE
visual errors in table row headers

### ISSUE THREAD

**Issue by connorjclark** [alex/nyt-2020-election-scraper#111]
![image](https://user-images.githubusercontent.com/4071474/98319632-cbd99a80-1fa6-11eb-973e-5cc063691d4c.png)

Maybe caused by #76? Revert and rework?

**Comment by sebsebmc** [comment]
We are aware and reverting

**Comment by WarrenBuffering** [comment]
Oh no, the tbody was supposed to be below the closing thead. I see you've reverted, but I can revisit this in the morning too. My fault
