### ISSUE TITLE
Scolling down with Shrink table mode is buggy

### ISSUE THREAD

**Issue by jawahar-vasanth** [alex/nyt-2020-election-scraper#114]
While scrolling down with 'shrink table mode' is buggy since the header for each state is overlapping on the data which is displayed

**Comment by jjarmoc** [comment]
There's been quite a few changes to the table header layout since this was opened. Does it look better now?  If not, can you post a screenshot of the problem you're seeing?

**Comment by jawahar-vasanth** [comment]
It was sorted 2 hrs after I raised the issue. Wonderful job guys. Made this election lot more interesting
