### ISSUE TITLE
More color-coding in tables

### ISSUE THREAD

**Issue by NickHeiner** [alex/nyt-2020-election-scraper#117]
![image](https://user-images.githubusercontent.com/829827/98320625-2c151000-1f98-11eb-865b-f1b4a6c86d03.png)

To make the tables easier to scan, it would be nice if more of the `td`s were highlighted. For instance, it would be great if the "Block Breakdown" column cells were highlighted according to which candidate won the breakdown.

**Comment by fractionalhare** [comment]
We don't want to add more color coding right now. I can see why this would be interesting, but we've had a few similar proposals and we're pretty much uniformly set against adding any more color indicators aside from who the current leader is.
