### ISSUE TITLE
Unable to run python file

### ISSUE THREAD

**Issue by saewitz** [alex/nyt-2020-election-scraper#122]
Hi, I'm trying to run the python file, but am getting this error: `ModuleNotFoundError: No module named 'git'`.

I ran `pip install -r requirements.txt`. Anyone else run into this?

**Comment by caerulius** [comment]
if requirements isn't working you can install the module directly via `pip install gitpython`

**Comment by sebsebmc** [comment]
There have been some reported issues on Windows and others with outdated versions of pip

**Comment by frewsxcv** [comment]
you'll hit that error when your python is not installing dependencies properly. since it's out of scope of this project, i'm going to close

**Comment by bandtank** [comment]
@saewitz I had a similar problem. See #177 for details even though it isn't exactly the same issue.
