### ISSUE TITLE
Explanation for Block Trend

### ISSUE THREAD

**Issue by NickHeiner** [alex/nyt-2020-election-scraper#125]
It would be nice if the UI had a summary of how the block trend is computed. The `i` tooltip trigger does not actually cause any tooltip to appear on hover.

![image](https://user-images.githubusercontent.com/829827/98322410-33d6b380-1f9c-11eb-8a22-2e78d22a91c3.png)

**Comment by enterprisey** [comment]
"Works on my machine." Bootstrap compatibility issues, maybe?

**Comment by jasperswallen** [comment]
It should have a summary. Do the other tooltips works?

<img width="210" alt="Screen Shot 2020-11-05 at 10 23 35 PM" src="https://user-images.githubusercontent.com/44964970/98322509-2d9d0300-1fad-11eb-97c1-fdb6b9406904.png">

**Comment by NickHeiner** [comment]
Heh, now it also works on my machine after refreshing the page. Maybe something with the live reload puts it in an incorrect state?

**Comment by enterprisey** [comment]
Yes, I think the live reload is breaking the tooltips. Maybe we could just replace the table rows if the headers haven't changed.

**Comment by bojanrajkovic** [comment]
Looks like when we hooked up live reload, we forgot to re-activate tooltips on refreshes. Should be an was fix.
