### ISSUE TITLE
Small markup change could enhance accessibility

### ISSUE THREAD

**Issue by sinabahram** [alex/nyt-2020-election-scraper#127]
Is it please possible to not have the first cell be a th? It forces screen readers to constantly read that out before hearing the value of each cell, which is all but unusable, and this data is otherwise so well structured.

So, where it says:
Arizona (EV: 11)

Can that please be a td or hopefully a caption, but just not a th please? That one fix, an 'h' to a 'd' will enable blind folks to hear this data so much more easily.

I would file a PR, but since I'm blind I don't know if I'll mess up your styling with the markup change.

Thanks in advance!

**Comment by thomasdesr** [comment]
Thanks! Tracking down someone to fix this!

**Comment by sinabahram** [comment]
Amazing, thank you very much!
