### ISSUE TITLE
Option to hide boring states

### ISSUE THREAD

**Issue by spanktar** [alex/nyt-2020-election-scraper#129]
NV & NC haven’t changed in ages. The ability to hide certain states, that would persist through a refresh, would save real estate. 

Great work so far!

**Comment by sebsebmc** [comment]
ANN believes all states are important!

**Comment by spanktar** [comment]
Agreed! But hiding things that won’t change tonight is also good! 😇

**Comment by sebsebmc** [comment]
Uh so mostly the issue is that if stuff changes we dont want the states shuffling around, see https://github.com/alex/nyt-2020-election-scraper/pull/119

**Comment by bojanrajkovic** [comment]
We closed a similar issue, this is mostly obviated by the collapsed table versions, and we don't want to introduce additional UX complexity, especially with live reload. Closing.

**Comment by spanktar** [comment]
I guess I’m not paying, so... 😉
Great work everybody!
