### ISSUE TITLE
Tiny UI bug: State flag is only partially hidden behind "Timestamp"

### ISSUE THREAD

**Issue by phuzion** [alex/nyt-2020-election-scraper#132]
As can be seen in my attached GIF, the state flag is hidden behind the Timestamp block. However, this doesn't fully hide the entirety of the flag. A small portion of the flag can be seen popping out from behind the Timestamp block.

![vote-thing-bug](https://user-images.githubusercontent.com/398094/98323356-9e491d00-1fb7-11eb-8ee7-e6d0fb30495d.gif)

**Comment by sebsebmc** [comment]
There are some PRs to try and fix the sticky headers which should help with this

**Comment by phuzion** [comment]
Seems fixed with moving the flags to the right side of the header. Thanks!
