### ISSUE TITLE
collapse/expand individual tables

### ISSUE THREAD

**Issue by rcoenen** [alex/nyt-2020-election-scraper#133]
the global expand/collapse tables feature is nice. But even better would be a feature to individually expand/collapse tables

**Comment by fractionalhare** [comment]
I think the use case for this (being able to quickly scan the entire page) is pretty well satisfied by having the tables collapsed by default now. It also wouldn't be a trivial change for the UI.

**Comment by rcoenen** [comment]
Well, not exactly the usecase I was interested in: I like to see historical data (expanded table) of 1 vs various others last 2/3 updates. That makes it easier to analyse 1 particular table in comparison to others in a dashboard mode. That is impossible when *all* tables are expanded. Especially since they keep growing.
