### ISSUE TITLE
feature request: henu at top with links to individual states

### ISSUE THREAD

**Issue by nanaze** [alex/nyt-2020-election-scraper#136]
rather than having to scroll through

**Comment by fractionalhare** [comment]
I am -1 on this. I think most of what you'd get out of this addition is accomplished with the Shrink Tables feature. Further, if we add this it could contribute to visual clutter. We'd rather err on the side of fewer features than added complexity.

**Comment by thomasdesr** [comment]
Thank for reaching out!

We're trying to keep things clean enough that we don't need a menu. And currently, we're pretty comfortable with the state of expand/shrink states.
