### ISSUE TITLE
Block trend computed incorrectly for latest GA data

### ISSUE THREAD

**Issue by adepssimius** [alex/nyt-2020-election-scraper#148]
![image](https://user-images.githubusercontent.com/5257052/98325843-bae85380-1fbd-11eb-8838-de61921bbbb0.png)
If the latest block was more trump votes, the biden block percentage should have decreased.

**Comment by bojanrajkovic** [comment]
No, it should increase? If Trump got more votes, Biden needs more votes...seems pretty clear.

**Comment by bojanrajkovic** [comment]
Oh, sorry, misread the column. :) Yep, something seems up with the trend...

**Comment by adepssimius** [comment]
nope, that's backwards. The hurdle should increase, but block trend should decrease.

**Comment by sebsebmc** [comment]
Ok, it could be that the 30k moving average has moved into more Biden friendly votes in the history

**Comment by axlekb** [comment]
Depends on what "fell off the back".  If what "fell off the back" was "more Trumpy" than the average then the block could go up for Biden.

**Comment by bellachp** [comment]
Yea the issue is that the moving average takes the entire last "block" needed to clear the 30k minimum. So the set can final result can change if a large block that was shifted one candidate falls out of the calculation.

**Comment by adepssimius** [comment]
Makes sense. Well done on this project all.

**Comment by bellachp** [comment]
i might be fixing it anyway. @adepssimius thanks for the catch if you want to check it on the latest it should make intuitive sense now.
