### ISSUE TITLE
Feature: Make hovering over 'Last Batch' list the states in the batch

### ISSUE THREAD

**Issue by bschuetze** [alex/nyt-2020-election-scraper#161]
eg:  
![image](https://user-images.githubusercontent.com/18507144/98327164-d34e8180-2042-11eb-925a-fbaa5b68cb5c.png)

Also could be made a link to the relevant table

**Comment by JohnMart** [comment]
Associating PR #207 for transparency. Bug fixes are prioritized over features. 👍

> thanks for the pr @JohnMart! we've agreed to slow down on adding new features and instead prioritize fixing outstanding bugs and cleaning up the UI and codebase. we're going to close this for now, but we can revisit it later if there aren't any merge conflicts. thanks again!

**Comment by bojanrajkovic** [comment]
This was fixed by #314, I think.
