### ISSUE TITLE
Images obscuring text

### ISSUE THREAD

**Issue by kitson1** [alex/nyt-2020-election-scraper#163]
The images of the state flags seem to be obscuring relevant text.
I'm using a Chrome Browser (Version 86.0.4240.111 (Official Build) (64-bit)), and it's looking like this:
![image](https://user-images.githubusercontent.com/74036393/98327389-5c24d900-1fc1-11eb-97ba-db305156ad21.png)

![image](https://user-images.githubusercontent.com/74036393/98327434-73fc5d00-1fc1-11eb-8c9c-99f679b3b4b2.png)

**Comment by sebsebmc** [comment]
We are looking into it!

**Comment by sebsebmc** [comment]
In the meantime we believe its an issue with live reloading so refreshing and/or disabling that should help

**Comment by kitson1** [comment]
Looks great after refresh.
Thanks!

**Comment by thomasdesr** [comment]
Thanks for the report @kitson1!

if anyone else is seeing something like this please feel free to reopen and share what you're seeing
