### ISSUE TITLE
Add "Apps using this data" section in README

### ISSUE THREAD

**Issue by wobsoriano** [alex/nyt-2020-election-scraper#169]
First of all, thank you for this awesome repo! I am currently using it in my [simple viz](https://election2020.vercel.app/).

Not really an issue but I think it would be nice if we can add a showcase section? Apps that are using this data.

I referenced this repo in my app's repo https://github.com/wobsoriano/election2020. Thanks!

**Comment by sebsebmc** [comment]
We don't want to endorse anything from this and also want keep outbound links to a minimum. I don't think we will be accepting PR's for a showcase listing.
