### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by asedeno** [alex/nyt-2020-election-scraper#173]
Thoughts on producing an rss file of the latest batches to drop?

**Comment by thomasdesr** [comment]
You beat me to filing this by seconds! We'd love to see an RSS feed :D

Related: #115

**Comment by asedeno** [comment]
I was thinking something pretty minimal: one entry per state, with a description containing the leader and margin, the timestamp from the latest entry for the state as the pubDate, and a combination of the two for the rss guid.

**Comment by asedeno** [comment]
@thomasdesr, thoughts on the sample output at https://github.com/alex/nyt-2020-election-scraper/pull/189#issuecomment-722904600?
