### ISSUE TITLE
Set repo URL to https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html

### ISSUE THREAD

**Issue by jennybc** [alex/nyt-2020-election-scraper#176]
Set repo URL to https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html

Sorry I this isn't amenable to a PR.

<img width="1751" alt="Screen Shot 2020-11-05 at 9 35 53 PM" src="https://user-images.githubusercontent.com/599454/98330391-2a0a7b80-1faf-11eb-9aef-610dbcfa990f.png">

**Comment by fractionalhare** [comment]
Hey, this is a good idea. I'll do that!
