### ISSUE TITLE
Bug: Relative time stamps changed to UTC

### ISSUE THREAD

**Issue by timroesner** [alex/nyt-2020-election-scraper#178]
A recent commit changed all relative times to UTC.
I agree that relative time stamps may not be the best, but at the very least we could display them as local time?

**Comment by therippa** [comment]
Agreed.  Was just poking through the commit history to find the offending PR, I believe it was #69 

The previous timestamps of "Last Batch: ___ minutes ago" was much more helpful and readable.

**Comment by rmhoward** [comment]
I was just about to comment on this. Local time or reverting back to relative time would be ideal. No one knows UTC.

**Comment by eldirinice** [comment]
I think relative time is better than just displaying a timestamp. It's easier to digest rather than having to do the time math yourself.

**Comment by frewsxcv** [comment]
fixed
