### ISSUE TITLE
Relative ‘Last Scraped’ so much better than absolute

### ISSUE THREAD

**Issue by johnbent** [alex/nyt-2020-election-scraper#180]
Ugh.  I can’t figure out which PR did this (it must have been combined in a PR that didn’t something else) but a recent PR changed the ‘Last Scraped’ value from being a relative thing like ‘3 minutes ago’ to being an absolute thing like ‘2020-11-06 05:26:59 UTC’.  We humans are not clocks/calculators.  Can we revert this please?

Current format:
Last scrape: 2020-11-06 05:26:59 UTC | Last batch: 2020-11-06 05:05:06 UTC

Previous format:
Last scrape: 10 minutes ago | Last batch: 17 minutes ago

Maybe a compromise where we do both?  But definitely not just the absolute thing only please.

**Comment by JAStanton** [comment]
probably this PR https://github.com/alex/nyt-2020-election-scraper/pull/90

**Comment by JoshGlazebrook** [comment]
Yes, please revert back to xx minutes/hours ago. Absolute timestamps are horrible for this. If we need them just have them show on hover.

**Comment by sanch03** [comment]
reverted

**Comment by frewsxcv** [comment]
fixed
