### ISSUE TITLE
Feature: Add support for Popular vote

### ISSUE THREAD

**Issue by bchee** [alex/nyt-2020-election-scraper#185]
It would be great to see the differential for the popular vote and the total outstanding votes are left.

**Comment by sebsebmc** [comment]
It is largely not a feature we are interested in, we want to focus on reporting data for states that could possibly flip (yes even AK, anything thats not been called). At this point the popular vote isnt expected to flip and we dont want to add more clutter.

Also we have no current code that deals with the popular vote.

**Comment by bchee** [comment]
Thanks for the reply. I see what you are saying. I would argue it is still valuable information especially for knowing how many votes in total haven't been counted and to use your own argument for AK, the popular vote is not likely to flip but is not called yet like AK. Although I think most would say the popular vote is "called" but there are 13 million votes still uncounted and the popular vote difference is 4 million so still "possible".

Regardless, you guys are running the project and have other priorities but if you guys are looking for something to add in the future I wouldn't count this out. Thanks again for the reply and love the project keep up the good work!
