### ISSUE TITLE
Highlight what just changed

### ISSUE THREAD

**Issue by hrag** [alex/nyt-2020-election-scraper#187]
I have notifications running for this site, and when I click through the notification and get to the site, I have no idea what's changed. Thinking it would be cool to highlight/underscore the state that just was updated.

**Comment by ryannerocha** [comment]
Sorry, how did you get notifications running? I saw it was an option earlier but I don't see the button up top anymore.

**Comment by razh** [comment]
@ryannerocha It's the **Enable Live Updates** button:

https://github.com/alex/nyt-2020-election-scraper/blob/d6dcc34836a62e09f897ec41e19e4ead7ac29855/battleground-state-changes.html.tmpl#L173

https://github.com/alex/nyt-2020-election-scraper/blob/d6dcc34836a62e09f897ec41e19e4ead7ac29855/battleground-state-changes.html.tmpl#L356-L364

**Comment by ryannerocha** [comment]
Oh, I see. Does that mean I have to run a certain branch to see it? Because
it's not showing up on the live page for me.

**Comment by ryannerocha** [comment]
Oh shoot nevermind, I misread that. Sorry, it's so late lol.

**Comment by graingert** [comment]
this can be done with css ":focus" selector and direct urls to the row: eg https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html#georgia-2020-11-06T14:24:48.231000
