### ISSUE TITLE
Vote Estimates for PA are wrong

### ISSUE THREAD

**Issue by rambleRamblePie** [alex/nyt-2020-election-scraper#190]
The vote estimates for PA are wrong. 

> ...the PA remaining votes is wrong, it's around 158k NOT 275k (275k was based on an initial estimate, 158k is the official count from here [www.votespa.com](https://www.votespa.com/About-Elections/Pages/Counting-Dashboard.aspx)  - note it says 163k because it hasn't updated from the last Philly drop). It shouldn't matter and I doubt it'll be close but just know the percentages that Biden needs to track are wrong.

[reddit comment](https://old.reddit.com/r/politics/comments/jozau7/discussion_thread_2020_general_election_part_57/gbblxi5/)

**Comment by alex** [comment]
We're just reflecting the NYT data here, this will update when the NYT updates it.

**Comment by alex** [comment]
(And the NYT will update it when Edison Research updates it.)

**Comment by rambleRamblePie** [comment]
Sorry about that. Love the site though!
