### ISSUE TITLE
Can we turn off the PR-updating bot?

### ISSUE THREAD

**Issue by enterprisey** [alex/nyt-2020-election-scraper#191]
It doesn't look like it's doing any good right now, and forces frequent rebases (unless I'm doing it wrong). Template changes are just gonna be reflected in the next update, right?

**Comment by fractionalhare** [comment]
It does force frequent rebases, which is an unfortunate artifact of the architecture. But it's important to get these PRs for last scrape notes on the page as well as timely updates as soon as they happen.
