### ISSUE TITLE
Error in Hurdle Percentage Estimates

### ISSUE THREAD

**Issue by victoriak2001** [alex/nyt-2020-election-scraper#194]
So I'm not much of a coder but decently good with numbers and I noticed a problem with the way the program is calculating the hurdle figures. I've run some calculations based on its numbers and I'm reasonably certain it's deriving the hurdles from this equation:

H = (100%)(D + R)/(2R)

where H = estimated hurdle percentage, D = vote differential, and R = estimated votes remaining.

This seems fairly accurate, but it's actually wrong. Let me explain why with the following system of equations:

L - W = D
L + W = R

where L = # of currently losing candidate's (Trump or Biden) remaining votes if they make the hurdle, W = # of currently winning candidate's (Trump or Biden) remaining votes if the other one makes the hurdle, and D and R are the same as what I defined them as before. 

The rationale here is pretty simple. If the currently losing candidate is to beat the currently winning candidate, then in the remaining votes, the losing candidate must beat the winning candidate by a margin greater than or equal to the current vote differential, D (i.e., the first equation). And obviously Biden and Trump's remaining votes have to sum to the total number of remaining votes, R (i.e., the second equation).

Solving by elimination, we get:

2L = D + R
L = (D + R)/2

Then we just divide L by R and multiply the quotient by 100 percent to get the hurdle percentage, H:

H = (100%)(D + R)/(2R)

As you can see, this is exactly the same equation that I said I believe the program is using now. So where's the error? It's actually in our original system of equations. Remember when I said Biden and Trump's remaining votes have to sum to the total number of remaining votes? That's only true if every single vote was cast for Biden or Trump. We're ignoring the small fraction of non-Biden, non-Trump votes (i.e., third-party, independent, and write-in votes). 

There's no perfect way to account for these votes since we don't know what the proportion of non-Biden, non-Trump votes will be among the remaining votes. However, we can approximate it by calculating that proportion for the votes already counted. Scaling down the right side of our second equation on this basis, our amended system of equations is:

L - W = D
L + W = R(B + T)/S

where B = # of current Biden votes, T = # of current Trump votes, and S = sum of all current votes.

Reworking the math, we find:

H = (100%)(D + R(B + T)/S)/(2R)

Even though the program's hurdle percentages tended to be only ~0.6 percent off from the ones I calculated using the amended equation, considering how close this race is, I think fixing the error is warranted. And while my equation is also flawed as it assumes the proportion of non-Biden, non-Trump votes won't change, estimating that proportion is far better than disregarding it altogether.

That being said, I'm a coding amateur at best and don't trust myself to work with the files. I'm just putting this out there so that someone who's better at this stuff than I am can make what I assume is a very small edit.

**Comment by tqbf** [comment]
This is a good issue! Our actual equation is even dumber than the one you derived, but you're right, we're not accounting for Libertarians. Looking into it!

**Comment by victoriak2001** [comment]
> This is a good issue! Our actual equation is even dumber than the one you derived, but you're right, we're not accounting for Libertarians. Looking into it!

No problem! I'm glad I could help. If you could, please let me know if it gets fixed. I think I'm supposed to close an issue when there's an associated pull request?

**Comment by tqbf** [comment]
Will do. Of course, we'll leave this issue open for now.

**Comment by thomasdesr** [comment]
Yep! We'll make sure the PR closes this issue when it gets merged (someone is taking a shot at a making fix atm).

**Comment by thomasdesr** [comment]
@AutumnMystic Thanks for the fantastic report! We've merged your suggested fix and the site should update shortly (<=5m) with better information.

**Comment by thomasdesr** [comment]
If you're curious about what was involved this should take you to the diff: https://github.com/alex/nyt-2020-election-scraper/pull/200/files

**Comment by victoriak2001** [comment]
@thomasdesr Thanks! I checked the new Georgia numbers and they match my figures.
