### ISSUE TITLE
Thoughts on Graph/Visualization?

### ISSUE THREAD

**Issue by philbb** [alex/nyt-2020-election-scraper#195]
What is the thinking on adding at least one graph per state to visualize the time-series evolution of the metrics?
What should the graph represent to be as useful and clear as possible?
Any suggestion on what library to use?

**Comment by philbb** [comment]
Does anyone who is good with Javascript / D3 want to help implement this:
https://www.d3-graph-gallery.com/graph/line_confidence_interval.html

I'm thinking
- 

- x = time

- y1 = current block trailing_candidate_partition

- y2 = trailing_candidate_partition moving average - 2 std deviations 

- y3 = trailing_candidate_partition moving average + 2 std deviations

- y4 = Hurdle moving average (dotted line)

**Comment by wobsoriano** [comment]
If anyone wants to enhance my simple viz https://election2020.vercel.app/

https://github.com/wobsoriano/election2020

**Comment by ZmjbS** [comment]
Great idea. I've been tinkering around with this:
![tmp](https://user-images.githubusercontent.com/1388975/98355355-eef16200-2019-11eb-83f6-a17218fa5742.png)
Basically the top (left) graph shows the total number of votes counted, the estimated number of votes, and a horizontal line showing the minimum number of estimated votes (representing the earliest point that the count will finish).

The bottom (left) shows the total number of votes for each candidate and a trendline. Would be useful to restrict the evaluated points to a more recent one, or even see if an exponential (relative to the total number of votes) would be a more accurate fit (seeing how the pace of the votes counted seems to be dropping, at least in Georgia).

The two plots on the right just zoom in on the interesting bit, which I've tuned by hand. One solution to this is to have a couple of sliders selecting the number of points evaluated for the fitted curve, and a zoomable map (either through a slider, but some plotting packages come with zoom features that allow the user to select a range on the map to zoom to).

Nice extra features would be a vertical line indicating the intersection of the fitted curves for counted+min_total and biden+trump.

**Comment by benlankamp** [comment]
First off, great work by all involved so far.

@zmbjs:  These graphs are great ideas. Are the trends based on the numbers that the scraper provides?

Personally, I've used the data to get an estimate of the final vote margins. I implemented graphs for this, though I used Highcharts and not D3. 
![margin-graph](https://user-images.githubusercontent.com/743959/98360541-48fa2380-202a-11eb-8c52-14b4ae69f611.jpg)

**Comment by ZmjbS** [comment]
> @zmbjs: These graphs are great ideas. Are the trends based on the numbers that the scraper provides?

The graphs show data that I typed in by hand every few hours, so the resolution is much lower than the scraper provides. Thought about writing something on top of the scraper but between work, kids and cooking I figured I'd just leave that to somone with a little more time.

The trendline is just a straight line fit to a hand-picked subset of the available data. I was pretty happy with it because all it shows is real data, and it's quite clear that the straight line isn't a reliable prediction, but rather an aid for one to mentally extrapolate the data.

**Comment by jjarmoc** [comment]
It looks like you've done some really nice work on visualizations! While we appreciate and respect the desire to look at the data in this way, the intent of the tool is largely to present a simple, visually uncluttered view of the raw data. Graphs and visualizations would be contrary to this design goal, and thus aren't something we wish to pursue at this time. 

We definitely encourage folks to fork and build upon the existing tool. For example, @saleemrashid has done some [great work on visualizations](https://saleemrashid.github.io/nyt-2020-election-scraper/) as well. 

Also, if you haven't yet found them, it may be of interest to note that the raw data is available in both [CSV](https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.csv) and [plain text](https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.txt) formats.

**Comment by radames** [comment]
hi all, just saw this graph made with a symlog scale!! 
https://observablehq.com/@markwhiting/votes-over-time

![image](https://user-images.githubusercontent.com/102277/98412600-16055f00-202d-11eb-8d60-0cc99743ba8a.png)

ps. also very easy to embed this live graph from observablehq @bojanrajkovic if you all are interested in add this to the main html page
