### ISSUE TITLE
Live updates infinite loops refreshing

### ISSUE THREAD

**Issue by deanputney** [alex/nyt-2020-election-scraper#198]
I've had a lot of trouble with live updates. It failed previously, now it continuously refreshes. Something seems broken. Is anyone else having this issue?

Chrome 84.0.4147.135

**Comment by MarcosCarballal** [comment]
I'm having this same issue. Firefox 82.0

**Comment by tockv** [comment]
Same issue. Chrome 86.0

**Comment by deanputney** [comment]
I think what might be happening is that the [check for if the current SHA is the same as the latest SHA](https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.html#L5757) is triggering an infinite loop before the page build can complete. That might be causing a race condition– and even if it's not the primary cause here I'd consider it a risk.

Doing a full page refresh like this is kind of dangerous to begin with, and can cause some really expensive loading. In the interest of suggesting something useful: Maybe output the SHA of the latest build to a file and then [check the latest commit in fetchLatestCommit against that instead](https://github.com/alex/nyt-2020-election-scraper/blob/master/battleground-state-changes.html#L5716). That way you can be sure the page was built before kicking off a refresh. It'll be better, but you might still have caching issues. 

You almost might as well force that commit check to be some offset from the last build time so you can be sure the build completed before checking and refreshing.

**Comment by samczsun** [comment]
If you open the page in a new tab, does it still get in an infinite loop? If so, mind pasting what your console logs look like?

**Comment by helix4u** [comment]
errors on the sha check like so https://i.imgur.com/l1JVYNs.png until rate limiter hit on commits?per_page=10 https://i.imgur.com/zPwZ97v.png 
X-Ratelimit-Limit: 60
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 1604681669
X-Ratelimit-Used: 60

**Comment by helix4u** [comment]
was working until a sec ago this: https://i.imgur.com/QXUksBk.png https://i.imgur.com/a0bujqe.png

**Comment by thomasdesr** [comment]
Hey @helix4u 

Your network log shows requests to the github API which we're not longer leaning on for updates. So if you hard refresh I think the issue you're hitting should go away.

Please let us know if it doesn't :D

**Comment by helix4u** [comment]
yeah, I think it was just a momentary thing... possibly related to revert-262-feature/gh-page-polling if it went live for a second before it was paused.
