### ISSUE TITLE
Show local time in tooltip instead of UTC?

### ISSUE THREAD

**Issue by smy20011** [alex/nyt-2020-election-scraper#204]
It's better to show the time in local time zone instead of UTC time in the time tooltip.

**Comment by fractionalhare** [comment]
The team is pretty neutral on this. It actually wouldn't add visual clutter, but we don't really want to invest time in a PR. If you wrote up a PR for us, we'd probably consider merging it though :)

**Comment by fractionalhare** [comment]
Hey there! The underlying data received from the NYT source is in UTC. We don't really want to add more client-side formatting to wrangle our JSON blob into local times.

**Comment by fishstik** [comment]
Displaying local timestamp tooltips does not require modifying the underlying data. PR #253 only modifies the displayed timestamps in the `html.tmpl`.
