### ISSUE TITLE
Hurdle Calculation is not correct...

### ISSUE THREAD

**Issue by xxxmagicxxx** [alex/nyt-2020-election-scraper#206]
Georgia Hurdle states 52.52
We do have 
votes_remaining = 7352
vote_diff = 463
votes required for Biden for draw: 3908 vs 3445 for Trump (dif 463)
3908 / 7352 is 53.15%

**Comment by Enivex** [comment]
See https://github.com/alex/nyt-2020-election-scraper/issues/194

**Comment by fractionalhare** [comment]
This is a commonly reported issue but please see: #194. The tl;dr is that the hurdle rate does not correspond to the block breakdown because we're not tracking third party candidates in the block breakdown.
