### ISSUE TITLE
Block Breakdown calculation seems off

### ISSUE THREAD

**Issue by Ipsider** [alex/nyt-2020-election-scraper#209]
There is an entry that shows 15 votes in a block, but the block breakdown shows a 50:50 split, which is not possible.
<img width="1668" alt="Screenshot 2020-11-06 at 10 50 07" src="https://user-images.githubusercontent.com/9433900/98352074-d8e5a080-201d-11eb-8425-193ef8076c5d.png">

**Comment by Enivex** [comment]
It's possible if Jo Jorgenson received an odd number of votes

**Comment by conerck** [comment]
Yea, The latest data block  showed 15 votes changed, but the absolute number of votes for Biden and Trump stayed the same (which would mean all 15 votes went to third party candidates).
