### ISSUE TITLE
Block Trend average incorrect after leader flip?

### ISSUE THREAD

**Issue by hugovk** [alex/nyt-2020-election-scraper#214]
Biden just took the lead in GA:

![image](https://user-images.githubusercontent.com/1324225/98352635-f3704780-2026-11eb-8963-c7cf6886613e.png)

> Trump is averaging 65.6%
> Biden is averaging 67.9%
> Biden is averaging 67.9%

The Block Trend for Trump looks like it's really the old one for Biden, so is Trump's average really 100% - 65.6% = 34.4%?

**Comment by codeaholics** [comment]
I came to report exactly this! :D I guess it's still reporting the Biden average.

**Comment by hugovk** [comment]
Duplicate of #210, #211, #212. May be fixed by https://github.com/alex/nyt-2020-election-scraper/pull/208.
