### ISSUE TITLE
Faulty blocks for North Carolina?

### ISSUE THREAD

**Issue by pyguy3** [alex/nyt-2020-election-scraper#217]
All blocks for North Carolina are *exactly* 50/50, with vote differential not moving. Data error or bug?

**Comment by conerck** [comment]
The absolute vote numbers in NC haven't changed for either candidates, but they match what is show on the nytimes site.
Either the updates are all votes for third party candidates or there is some other tabulation correction going on, at the times.

**Comment by MikeJayDee** [comment]
They are probably only updating estimated remaining votes.

**Comment by pyguy3** [comment]
Ok, if it matches the underlying data source it is not a bug. Thanks for looking into it.
