### ISSUE TITLE
Block Trend goes wrong when In the lead changes compared previous timestamp  (see latest on georgia).

### ISSUE THREAD

**Issue by Renevb1970** [alex/nyt-2020-election-scraper#222]
On Georgia, it says "Trump is averaging 65.6%" on latest timestamp. That is the averaging for Biden. Trump is averaging around 35%. It looks as if it takes a moving trend for the candidate who is the new lead, but it should take the moving trend for the candidate that is the new follower.

**Comment by NickBarnes** [comment]
The code seems to assume that the second-place candidate for each block is the same.

**Comment by frewsxcv** [comment]
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215
