### ISSUE TITLE
Maths on trailing average of blocks seems wrong

### ISSUE THREAD

**Issue by mitchellpalmer** [alex/nyt-2020-election-scraper#223]
Thanks for this great tool, but I think the Biden lead in Georgia has broken the trailing average of blocks.  
![IMG_0055](https://user-images.githubusercontent.com/67769218/98359462-3ea84b80-2063-11eb-9e54-e8bb566ae370.jpeg)

**Comment by JJ** [comment]
Looks like it's not taking into account the fact that the winner has flipped.

**Comment by bobowen** [comment]
I was just about to file the same thing.
Looks like it is picking up the trailing name, i.e. now Trump, but the average is still Biden's.

**Comment by jimm89** [comment]
The fix is a simple one here - in the function "compute_hurdle_sma", the function looks at the votes for the candidate that was trailing *at each step* - so Biden's votes are being counted. What needs to happen instead of that the votes are aggregated over the candidate trailing only in the first step.

I can fix this if so desired, or can leave to the many others already contributing if too many cooks spoil the broth. Let me know if you want me to do this.

**Comment by JJ** [comment]
This needs kind of major refactoring. Variables refer to candidate_1 and candidate_2, no particular candidates. @jimm89 please go ahead and have a go at it, but I'm afraid it's not going to be so simple.

**Comment by JJ** [comment]
This seems to be the thing:

https://github.com/alex/nyt-2020-election-scraper/blob/6fe722143ed429d32731b4ef5a1718e8e613f61c/print-battleground-state-changes#L146-L147

I would say `agg` needs to become a dictionary indexed by the candidate name. But, as said, major refactoring is going to be needed.

**Comment by mccambridge** [comment]
It does look like the block average is having an issue after a lead change. I’d also like to say thanks for putting this amazing project together.

**Comment by JJ** [comment]
This here, which is a bit further up:
https://github.com/alex/nyt-2020-election-scraper/blob/6fe722143ed429d32731b4ef5a1718e8e613f61c/print-battleground-state-changes#L260-L265
needs to be refactored to make votes received a hash again.

**Comment by jimm89** [comment]
https://github.com/alex/nyt-2020-election-scraper/pull/215

Someone else seems to be attempting it.

**Comment by JJ** [comment]
Working on this now...

**Comment by JJ** [comment]
Tried to fix it, but it's still wrong. The votes are now tallied by name, but still they are sent to that function positionally, so averages are very wrong. Here's my pr #227. Moving it to draft, feel free to work on that.

**Comment by JJ** [comment]
Closed the PR I think #215 is right.

**Comment by frewsxcv** [comment]
thanks for the bug report! this is now fixed by https://github.com/alex/nyt-2020-election-scraper/pull/215
