### ISSUE TITLE
Is this the correct way to credit / license?

### ISSUE THREAD

**Issue by benlankamp** [alex/nyt-2020-election-scraper#224]
First of all, great initiative and excellent work by all involved! Just a quick check - I am using the data files that you are generating on a page (https://us2020.benlankamp.nl/) that shows current and projected final voting margins. I included the link to this Github and the MIT license: Site: https://us2020.benlankamp.nl/#data-license 

Just wanted to check if this is the proper way of crediting and licensing.

**Comment by atuttle** [comment]
@benlankamp is there a way to make a contribution to yours? I'd love to be able to make it full-screen on one of my monitors all day today but it doesn't handle that much screen-width well. I'd be happy to tweak it if I could. :)

**Comment by atuttle** [comment]
For now I've used [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe) to add the following CSS to the page:

```css
@media (min-width: 1900px) {
    .grid {
		grid-template-columns: 33% 33% 33%;
    }
}
```

If you added this, it would enable a 2x3 grid, which fits everything nicely in a full-screen configuration on large monitors; and by using media queries to target large screens, it won't have any effect for viewport widths < 1900px. 😄 

![image](https://user-images.githubusercontent.com/46990/98367500-bf375f80-2003-11eb-946b-ccea40010dff.png)

**Comment by benlankamp** [comment]
@atuttle I'll make a repository in a minute, but I have already put in your suggestion.

**EDIT**: public repository: https://github.com/benlankamp/us-2020-scraper-viz, so I can accept PR's.

**Comment by fractionalhare** [comment]
Great project! Yep, that looks like a fine way to license/cite this project :)
