### ISSUE TITLE
trend is wrong just after a switch in leading candidate

### ISSUE THREAD

**Issue by RolfHut** [alex/nyt-2020-election-scraper#226]
See Georgia: Trump is not doing 67% percent over the last 30k votes, he hasn't been above 50%. I believe the Biden numbers are used when he was in the lead.

**Comment by ziban** [comment]
+1. I took a screenshot. 
<img width="1411" alt="Screen Shot 2020-11-06 at 2 37 59 PM" src="https://user-images.githubusercontent.com/5151782/98362170-d4c97b00-203d-11eb-8400-68aa3a8630ae.png">

**Comment by JJ** [comment]
See #223

**Comment by alar77** [comment]
Confirmed, If fixing is hard, could you just put a note on it?

**Comment by jimm89** [comment]
https://github.com/alex/nyt-2020-election-scraper/pull/215

@rachetfoot seems to believe he's fixed the issue

**Comment by RolfHut** [comment]
copy of #223, sorry for not checking.
