### ISSUE TITLE
Recalculate Block Trend when lead changes

### ISSUE THREAD

**Issue by OpenSorceress** [alex/nyt-2020-election-scraper#229]
When the lead changes, the Block Trend ascribes the trend from the previous loser to the new loser instead of recalculating.

**Comment by OpenSorceress** [comment]
![block-trend](https://user-images.githubusercontent.com/1856244/98366758-23552600-1ffa-11eb-8e42-23c37b5c9031.jpeg)

**Comment by vizistep** [comment]
Try refreshing, seems to be fixed already

**Comment by rimrul** [comment]
This is already fixed by #215

**Comment by frewsxcv** [comment]
yep! should have been fixed by #215. just need to refresh

**Comment by mairallenwilliams** [comment]
Uhm, did the fix break something else? The trend looks wrong for Pennsylvania now.
