### ISSUE TITLE
new Block breakdown in PA incorrect

### ISSUE THREAD

**Issue by nirhur** [alex/nyt-2020-election-scraper#231]
it says Trump 82.5% / 17.5% Biden but the Vote Differential went down (I believe it should be Trump 17.5% / 82.5% Biden)
![PA](https://user-images.githubusercontent.com/3276495/98367484-63d69300-203e-11eb-81c3-6ec15b92d80c.png)

**Comment by MarisaKirisame** [comment]
Another problem here is that vote change is negative. feature or a bug?

**Comment by helix4u** [comment]
it broke the PA totals as well? https://i.imgur.com/x1Yj4fF.png

**Comment by spraot** [comment]
The change is negative because there are now more estimated votes remaining. The negative value apparently reverses the block breakdown.

**Comment by spraot** [comment]
Actually, the Change value in the first row of PA and NV is clearly wrong, if it's supposed to be the change in remaining ballots.

**Comment by conerck** [comment]
> Actually, the Change value in the first row of PA and NV is clearly wrong, if it's supposed to be the change in remaining ballots.

The tooltip indicates that it is the actual number of votes reported in this block, not the change in remaining votes. If the remaining estimates were perfect, this would be equal, but they are estimates, which could be adjusted without any change in actual counted votes.

**Comment by spraot** [comment]
@conerck That makes sense, but how can a negative number of ballots be reported?

**Comment by rimrul** [comment]
@rachetfoot maybe a batch was recounted or some corrected a data entry mistake?

**Comment by conerck** [comment]
I'm guessing reports being corrected.
E.g. in the -280 Update in PA the vote totals changed from

Trump 3,286,171  -> 3,285,943 (-228)
Biden 3,267,942 -> 3,267,896 (-46) 
The remaing 6 votes probably went to third party candidates.

**Comment by titanous** [comment]
I'm going to close this. As others have pointed out, this can happen when new votes are reported at the same time that the estimated remaining votes change. There's not much we can do about that.
