### ISSUE TITLE
State flag images made state text unreadable for several states

### ISSUE THREAD

**Issue by vecima** [alex/nyt-2020-election-scraper#233]
Text should be readable no matter the bg color.  Suggest white text with black outline/shadow.

**Comment by jjarmoc** [comment]
Can you add a screenshot of what you're seeing? I'm not sure I understand.

The flag images are right justified, and the text is left justified. There shouldn't be any text over the flag images unless you have a really narrow window.

**Comment by titanous** [comment]
This was a live reload bug that is now fixed. Thanks for reporting it!
