### ISSUE TITLE
Add future projections based on per-county stats

### ISSUE THREAD

**Issue by jmarantz** [alex/nyt-2020-election-scraper#239]
I've been manually looking at the NYT site, looking for counties in GA or PA with significant uncounted votes remaining, and projecting out an expected potential vote delta based on the voting balance so far.

Currently the election-scraper is only looking at past data, but it could do much better projections than I can manually
 - it could analyze all the counties systematically rather than manually hovering over the map looking for counties with uncounted votes
 - it could in some cases do better projections based on recently-counted votes rather than using all the votes, including in-person. An example where that would make a huge difference is Erie, PA.

Maybe the projections feature is beyond the intended scope of the current site, in which case a parallel site with projections, sharing the same scraping infrastructure, could provide a much richer experience than anything I've seen so far on news sites.

**Comment by fractionalhare** [comment]
We don't really want to get into the projections game, and do feel it's outside the scope of this project. A few sibling projects have tried to tackle this though; this might be of interest to you: https://saleemrashid.github.io/nyt-2020-election-scraper/.

I do agree projections would be useful, but the project doesn't want to be that rich :) It really is just intended to be tabular data with history and some calculations.
