### ISSUE TITLE
linking to a specific timestamp causes the `position: sticky` thead to overlap with the focused element

### ISSUE THREAD

**Issue by graingert** [alex/nyt-2020-election-scraper#242]
eg: https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html#pennsylvania-2020-11-06T13:52:37.632000

**Comment by bryanhelms** [comment]
Just curious, what browser are you on? I'm able to reproduce the problem as you describe it on Firefox, but the deep links don't even work at _all_ for me on Chrome or Edge Chromium.

**Comment by bojanrajkovic** [comment]
Should be fixed by #312, please reopen if it's not!
