### ISSUE TITLE
Block Breakdown and Block Trend percentages not comparable to Hurdle percentages

### ISSUE THREAD

**Issue by vizistep** [alex/nyt-2020-election-scraper#245]
I know the calculation of Hurdle has been changed to account for votes for other candidates, which makes sense. But this creates (relatively small, but still) a problem. Because of this, you cannot really compare the Hurdle percentages to Block Breakdown/Trend percentages and immediately see, if the trend is sufficient for a flip anymore, because Block Breakdown/Trend only account for Biden/Trump votes. This might not be a big issue (you can still check if the Hurdle percentage goes up or down, for instance), but I wanted to flag it anyway, because it might not be immediately obvious.

**Comment by vizistep** [comment]
The easiest solution would probably be to have Block Breakdown/Trend also take into account third party votes.

**Comment by fractionalhare** [comment]
Please see #194.

**Comment by vizistep** [comment]
Thanks, the problem I was describing was a result of the solution implemented in #194 (i.e. taking account for third party votes only in Hurdle and not in Block Breakdown and Trend), but nevermind.

**Comment by vizistep** [comment]
> Please see #194.

Thanks, the problem I was describing was a result of the solution implemented in #194 (i.e. taking account for third party votes only in Hurdle and not in Block Breakdown and Trend), but nevermind.
