### ISSUE TITLE
Sort tables by last update timestamp in descending order

### ISSUE THREAD

**Issue by mindrones** [alex/nyt-2020-election-scraper#246]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

[ ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page

**Is your feature request related to an issue? Please cite the issue.**

Just a minor suggestion to make it easier to find the table containing the last update (when we click on the notification and land on the page, we need to search the last update visually).

**Clearly describe the solution you'd like**

It would be pretty handy to have tables sorted by last updated, so that the table containing the most recent update is always the first in the stack.

**Comment by jjarmoc** [comment]
This would result in states changing positions as updates come in. 
It seems like it would be kind of jarring for things to just re-order themselves.

**Comment by fishstik** [comment]
I'd actually prefer ordering tables by last update time. Working on a feature that will add a setting to toggle between this and alphabetical order.

**Comment by bojanrajkovic** [comment]
Thank you for opening this issue. We don't want to add this feature, as it would be visually jarring.
