### ISSUE TITLE
Add recount information for each state and current status of race as it relates to recount

### ISSUE THREAD

**Issue by fsmontenegro** [alex/nyt-2020-election-scraper#249]
Each state will have rules about when a recount is in the cards. It would be helpful to indicate if, the current differential between candidates still leaves the state within margin for an automatic recount.
See here for more info - https://www.nbcnews.com/politics/2020-election/recount-laws-key-states-presidential-race-n1246618

**Comment by titanous** [comment]
Thanks for the suggestion! We're trying to keep things simple by sticking to a single data source, and this information isn't available in the NYT JSON, so we won't be adding this. However, you should feel free to make your own fork of this project that has this info.
