### ISSUE TITLE
Clicking on a notification opens a page with a 404

### ISSUE THREAD

**Issue by HughMacdonald** [alex/nyt-2020-election-scraper#252]
When I click on a notification (Windows 10, Chrome), it opens up https://alex.github.io, which gives me a 404, rather than the full page at https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html

**Comment by fractionalhare** [comment]
Thanks for the heads up, looking into this.

**Comment by fractionalhare** [comment]
@HughMacdonald This *may* be fixed by the PR I just merged. Let me know if not though!

**Comment by HughMacdonald** [comment]
Yup - that worked for me - thanks!

**Comment by ChristopherW** [comment]
Loaded site within last 15 minutes and enabled then clicked on a notification for the first time, it took me to the root with a 404.

**Comment by zacjohnston** [comment]
Just got a 404
