### ISSUE TITLE
Add simple table of contents to jump to anchors for individual state tables

### ISSUE THREAD

**Issue by nclu** [alex/nyt-2020-election-scraper#254]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

[ ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**

**Comment by fractionalhare** [comment]
With the current amount of data we have and the number of remaining states, we're not going to implement this.
