### ISSUE TITLE
Hurdle calculation is wrong

### ISSUE THREAD

**Issue by brentonstrine** [alex/nyt-2020-election-scraper#257]
Hurdle calculation doesn't seem to include the uncounted votes. 

Example:

> Biden ahead by 10 votes.
> 100 uncounted votes left. 
> 
> Hurdle for Trump would be`(100 / 2) + 10`. 

I.e. half the remaining votes plus the difference.

**Comment by fractionalhare** [comment]
This is a commonly reported issue but please see: https://github.com/alex/nyt-2020-election-scraper/issues/194. The tl;dr is that the hurdle rate does not correspond to the block breakdown because we're not tracking third party candidates in the block breakdown.
