### ISSUE TITLE
show percentage of votes remaining

### ISSUE THREAD

**Issue by mennucc** [alex/nyt-2020-election-scraper#258]
hi. Fantastic page, we are really enjoing.

In the columnt "votes remaining" may you show the percentage as well as the absolute number?

For example, in Georgia it would be 4500 / 5000000 * 100 = 0.09%

but in Penn it would be 141000 / 6600000  * 100 =  2.13%

thanks 
a.

**Comment by noobyogi0010** [comment]
Hi!
I would love to add this functionality.
Can you guide me with where I've to do the changes?
Thanks.

**Comment by fractionalhare** [comment]
Hey there, we discussed this internally and don't really want to add this functionality. Part of the problem with this is that the votes remaining is already an unofficial estimate, and we don't want to add more information which is fundamentally uncertain.
