### ISSUE TITLE
Scrolling Table Update killed Mobile Experience

### ISSUE THREAD

**Issue by mmayers12** [alex/nyt-2020-election-scraper#259]
The latest update adding horizontal scroll bars killed this site on mobile for me.

I used to be able to zoom out and get all column on the screen for quick scanning of all the data, but now it's impossible to do so.  I constantly have to scroll left and right to be able to compare columns on opposite sides of the tables.  This makes me not want to use the site anymore as it's too unwieldy.

Please revert.

**Comment by Raitab** [comment]
Also coming here to make this issue. 
https://github.com/alex/nyt-2020-election-scraper/pull/240 seems to have made the site more responsive but scrolling large tables is horrid user experience, especially when I have specific columns I want to look at that are nowhere near the title/state of the table (Georgia, Pennsylvania, etc)

**Comment by shivamgulati1991** [comment]
+1 on the above , the mobile US has gone messy.
Great effort overall.

**Comment by thomasdesr** [comment]
Sorry about that!

We've merged something we think will fix that behavior! Please re-open if you still find yourself trapped in horizontal scrolling hell after a refresh.

**Comment by mmayers12** [comment]
It's working perfectly now, thanks for fixing so quickly!
