### ISSUE TITLE
Clicking "Enable Live Updates" or "Expand Tables" does nothing

### ISSUE THREAD

**Issue by zacjohnston** [alex/nyt-2020-election-scraper#269]
**Describe the bug**
The buttons used to work for me, but now they don't change state or have any effect.

 - OS: Ubuntu 20.04
 - Browser: Chrome

**Comment by simpat1zq** [comment]
Same on WIndows 10/Firefox and Chrome.

**Comment by thomasdesr** [comment]
Hey! Thanks for the report.

We just fixed this in #268 which should finish rolling out in the next few minutes.
