### ISSUE TITLE
Lead count appears incorrect.

### ISSUE THREAD

**Issue by vikramrojo** [alex/nyt-2020-election-scraper#271]
**Describe the bug**

The lead count seems incorrect for most states.

**To Reproduce**
See PA.
``Biden leads with 3,302,977 votes`

**Expected behavior**
Lead is closer to 6000.

**Comment by helix4u** [comment]
That line is prefaced with "Total votes:" and is correct. What you seem to be looking for is the "Vote Differential" column based on your described expected behavior.

**Comment by sebsebmc** [comment]
The pedantic answer is that we say he leads "with" not "by" 3 million votes.

**Comment by vikramrojo** [comment]
ah, sorry. thank you.
