### ISSUE TITLE
Timestamp column - could you show the last update time vs. only "XX minues/hours ago"

### ISSUE THREAD

**Issue by 1972silver** [alex/nyt-2020-election-scraper#275]
**Clearly describe the solution you'd like**

Timestamp column - could you show the last update time vs. only "XX minutes/hours ago."   In case the screen has not refreshed one can validate when results were last posted.

Great job on this app!!!

**Comment by titanous** [comment]
Hi, thanks for filing an issue!

The relative timestamps are automatically updated every minute while the page is open, so they should always be up to date. You can see a localized absolute timestamp by hovering. If any of this behavior isn't working as expected, please reopen this issue!

**Comment by 1972silver** [comment]
Thanks!  Did not notice the hover control.
