### ISSUE TITLE
Please display the vote differential calculation in the state header

### ISSUE THREAD

**Issue by 1972silver** [alex/nyt-2020-election-scraper#276]
**Clearly describe the solution you'd like**

Please display the vote differential calculation in the state header. 

**For example:**

**Current**
Total Votes: Biden leads with 3,310,371 votes, Trump trails with 3,296,961 votes. 

**Proposed**
Total Votes: Biden leads with 3,310,371 votes, Trump trails with 3,296,961 votes.   Differential is:  13, 410

**Comment by thomasdesr** [comment]
Hey! Thanks for the Issue & PR.

I think the data you want is already in the nearest table entry:
![image](https://user-images.githubusercontent.com/681004/98414270-0c89f000-2049-11eb-985c-d8264b761212.png)

Please feel free to re-open if I'm missing something :D

**Comment by 1972silver** [comment]
Yep, I now see that.  From a UI perspective it would be nice seeing the differential at a quick glance with the total numbers, but your suggestion also works.
