### ISSUE TITLE
Show Block Trend for both candidates

### ISSUE THREAD

**Issue by 1972silver** [alex/nyt-2020-election-scraper#277]
**Clearly describe the solution you'd like**

Show the Block Trends for both candidates

**Comment by bellachp** [comment]
Thanks - this is a great and simple idea and would be incredibly useful in a race with more than 2 candidates, if not required! At this point the focus is on less clutter on the chart though so we'll be leaving it as an optional future enhancement.

**Comment by bojanrajkovic** [comment]
This would be visually noisy, and you can just do `100 - whatever` pretty easily.
