### ISSUE TITLE
Detail box will flash if cursor is just on the edge of the box

### ISSUE THREAD

**Issue by matthews-stripe** [alex/nyt-2020-election-scraper#281]
![flashing](https://user-images.githubusercontent.com/51676362/98407429-83f95880-2024-11eb-9698-ba5790405c14.gif)

**To Reproduce**
1. Place your cursor on one of the pieces of text with a detail view
2. Slowly move your cursor up until the detail disappears
3. Slowly move your cursor down until the detail reappears.
4. Repeat 2-3 until your cursor is on the exact edge. The detail box will begin flashing without any further cursor movement.

**Expected behavior**
The detail box will not flash.

**Screenshots**
Gif above

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Browser: Google Chrome.
 - Version, Browser: 86.0.4240.183 (Official Build) (x86_64)
 - Version, Webpage: Not sure. Gif was recorded approximately 11:30am PST on 11/6/2020

**Additional Information** 
I was using the laptop's trackpad, not an external mouse.

BTW, thank you for making this! I've been using it to watch election results and I appreciate that you've been updating the tool and adding features these last few days.

**Comment by titanous** [comment]
Thanks for the precise report! We're just using the builtin Bootstrap tooltip library, and I suspect this is a debounce bug there. I'm not convinced this is worth digging further into, what do you think?

**Comment by jjarmoc** [comment]
I'm pretty sure I fixed this in PR #272, and I'm unable to repro now (despite trying for longer than I'd like to admit).

@matthews-stripe How does it look on your end?

**Comment by thomasdesr** [comment]
I was also able to repro it but agree with @titanous I don't see this as something we need to quick fix. If someone else feels differently we'd be happy to take a PR :D

**Comment by bojanrajkovic** [comment]
@matthews-stripe, if you can confirm if this is fixed & close it, or check if it's still an issue, that would be great.

**Comment by matthews-stripe** [comment]
Looks fixed to me. 👍
