### ISSUE TITLE
negative block breakdown

### ISSUE THREAD

**Issue by MarisaKirisame** [alex/nyt-2020-election-scraper#283]
![image](https://user-images.githubusercontent.com/3397377/98409375-8f01b800-2027-11eb-949d-1456ca84e333.png)

**Comment by shivamgulati1991** [comment]
was literally about to report this

**Comment by alex** [comment]
This happens when a state releases new votes _and_ changes the estimated number of votes remaining at the same time. As you can see votes remaining changed by 1, but vote differential changed by 5. It leads to edge cases like this. Not much to be done unfortunately.
