### ISSUE TITLE
Display the margin of lead in the state header

### ISSUE THREAD

**Issue by xkahn** [alex/nyt-2020-election-scraper#287]
**Is your feature request related to an issue? Please cite the issue.**
Since there are recounts associated with margins of final vote counts, the lead margin is an important piece of information.

**Clearly describe the solution you'd like**
Just display the margin percentage in the state header. Bonus would be the list the margin needed to avoid an automatic recount or a recount challenge for that state.

See: https://github.com/alex/nyt-2020-election-scraper/pull/265

**Comment by alexkozler** [comment]
The latest vote margin/differential is always listed on the newest batch, so why would it need to be duplicated in the header?

**Comment by slowbro** [comment]
I think they are referring to the percentage margin, which is usually the number stipulated for automatic recounts.

**Comment by noobyogi0010** [comment]
Hi!
I would love to work on this issue. Can you help me with getting started?
Thanks.

**Comment by ryannerocha** [comment]
@noobyogi0010 I think this was already completed here https://github.com/alex/nyt-2020-election-scraper/pull/265

**Comment by noobyogi0010** [comment]
@ryannerocha Okay, thanks.

**Comment by titanous** [comment]
We've added the vote share percentage to the table header.
