### ISSUE TITLE
Dynamic Block Trend?

### ISSUE THREAD

**Issue by darylantony** [alex/nyt-2020-election-scraper#289]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

[ ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page
[ ] - changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**

Currently, Block Trend, is a function of the last 30k votes.  However, right about now, the votes remaining in Georgia are between 3-4k and the inbound "blocks" are being counted in tallies of low 100s or less.

Perhaps, Block Trend could be changed or annotated so that we might see the average or trend over a smaller scale?

That is, with 4k votes left in Georgia, the 31% Trump trend over the last 30k votes seems to be diluted a little too much and I'm very, very interested in the smaller trend; perhaps the trend over the "last ten reporting blocks"? or something like that.

**Comment by darylantony** [comment]
Perhaps, the Block Trend could be calculated as a proportion of the votes left to count?

thanks for doing this Alex and co.  and hello from the Melbourne Django community — https://www.meetup.com/MelbDjango (I'm the organiser of this over the last 10 years

**Comment by saleemrashid** [comment]
Hi! :wave: Thanks for the clear and detailed issue!

I completely agree that 30k doesn't work as well with so few votes remaining, and I think your proposed solution might be better than using a fixed number.

Unfortunately, it would not be ideal to change the number at this time, as it would create confusion. Additionally, we no longer have reliable estimated votes data to calculate the hurdles for Georgia, so it probably wouldn't help so much.

**Comment by bellachp** [comment]
> Perhaps, the Block Trend could be calculated as a proportion of the votes left to count?

I _do_ like this idea. Thanks!

We initially chose 30k because it was a good proportional size to the remaining votes for GA & PA, the two key states to pay attention to at creation. At this point, having it vary by state would likely make it more confusing - and we have somewhat unreliable <votes remaining> numbers to begin with (see GA now). I think this is a good issue to keep for any future development.

**Comment by darylantony** [comment]
Roger that.  Thanks kindly guys.
