### ISSUE TITLE
Trailing candidate "needs 0.00%" when Votes Remaining (est) goes negative

### ISSUE THREAD

**Issue by scottleibrand** [alex/nyt-2020-election-scraper#290]
Georgia's votes counted just exceeded the estimated votes outstanding, causing Votes Remaining (est) to go negative, and the Hurdle to switch to "Trump needs 0.00% [-70.332%]"

Georgia (EV: 16)Total Votes: Biden leads with 2,455,433 votes, Trump trails with 2,451,170 votes.
--

3 minutes ago | Biden | 4,263 | -3,458 | 7,151 | Biden 69.0% / 31.0% Trump | Trump is averaging 31.0% | Trump needs 0.00% [-70.332%]

**Comment by scottleibrand** [comment]
The underlying source of the negative Votes Remaining is described in more detail in #292

**Comment by alex** [comment]
The #294 merged, I believe this is fixed as well.

**Comment by scottleibrand** [comment]
Yep, looks good now, thx.
