### ISSUE TITLE
Columns not aligned

### ISSUE THREAD

**Issue by AustinShalit** [alex/nyt-2020-election-scraper#295]
**Describe the bug**
Columns are no longer aligned. I think this is caused by #294 

**Expected behavior**
Columns are aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/3799260/98421086-91c7d180-2056-11eb-9d68-2e6a6963489c.png)

**Desktop (please complete the following information):**
Safari

**Comment by titanous** [comment]
Thanks for the report! We're on it! (we wanted to get that PR out fast even if it made the layout a bit broken)

**Comment by tahg** [comment]
Columns were never aligned.  The columns in each table were based on the relative widths needed to contain the data.  This already varied enough in the Timestamp column to make it somewhat noticeable. It's just that "Unknown" in the Hurdle column being so much shorter makes the issue much more obvious.

**Comment by titanous** [comment]
Fixed in #300.
