### ISSUE TITLE
Option to notify only if the Change is significant

### ISSUE THREAD

**Issue by konklone** [alex/nyt-2020-election-scraper#296]
Idea is to offer an option (or potentially default?) to notify but only if the Change amount is above a reasonable number. 100? 500? 1000? I think if you just made an opinionated choice and offered a "Notify if above X" button it would go a long way.

Responding to this:

![image](https://user-images.githubusercontent.com/4592/98422274-16f3bc00-2040-11eb-97db-eb1188d2dc11.png)

**Comment by MrMicrowaveOven** [comment]
Have notifications been removed?  I don't see them where they used to be.

![image](https://user-images.githubusercontent.com/16297628/98423087-6c30cd00-2042-11eb-94cc-c908e1422ba9.png)

**Comment by titanous** [comment]
@MrMicrowaveOven Notifications are on when live updates are enabled as long as you have allowed the notification permission for the site (you can check the site settings in your browser to confirm that they are enabled).

**Comment by MrMicrowaveOven** [comment]
@titanous Ah, got it.  There was a button for notifications before and I was confused.

**Comment by bojanrajkovic** [comment]
This would require a lot of configuration -- at this point, it feels like adding significant options/configuration is more work than is necessary.
