### ISSUE TITLE
Request: click the timestamp to pop up the exact time

### ISSUE THREAD

**Issue by sxflynn** [alex/nyt-2020-election-scraper#298]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

[x ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page
[ ] - changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**

It would be wonderful if I could click the timestamp where it says X days ago and it hovers a pop up that tells you the exact day and time that block event occurred. Not too dissimilar to hovering your mouse over the tooltip to get an explanation of each column.

**Comment by tahg** [comment]
It already definitely does this. (Just hold your mouse over it until it pops up.)

**Comment by titanous** [comment]
Yeah, hover and it should show up. Please re-open this if it's not working.

**Comment by sxflynn** [comment]
> Yeah, hover and it should show up. Please re-open this if it's not working.

On iOS / touch interface if you tap the "x ago" nothing happens. There's no way to view the time.
