### ISSUE TITLE
When all votes go to one candidate, the block trend is miscalculated

### ISSUE THREAD

**Issue by dddomin3** [alex/nyt-2020-election-scraper#301]
Let me know if you need more info:
<img width="1508" alt="Screen Shot 2020-11-06 at 4 16 46 PM" src="https://user-images.githubusercontent.com/5600649/98423301-7acfb200-204b-11eb-8778-93eb2db7d8e5.png">

**Comment by abdellahrk** [comment]
[aurora](https://aurora.cm)
