### ISSUE TITLE
"Change" in what?

### ISSUE THREAD

**Issue by dabrahams** [alex/nyt-2020-election-scraper#306]
**Describe the bug**

I expected the change column to be reporting the change in the vote margin, but it seems instead it's the number of new votes in the report?  Maybe?  I'm guessing.  It should be better named.

Also, whatever it's reporting, I'd prefer to see the change in the vote margin 😉

**Comment by titanous** [comment]
Can you please provide a screenshot of the data that's confusing you?

**Comment by fractionalhare** [comment]
@dabrahams The tooltips are there to clarify this point.

**Comment by bojanrajkovic** [comment]
#263 seems to be asking for the same thing. Closing this in favor of that, please reopen and clarify if they're different.

**Comment by mirekphd** [comment]
> please reopen and clarify if they're different.

@dabrahams could you reopen please? I closed mine in favour of yours.

**Comment by mirekphd** [comment]
> Can you please provide a screenshot of the data that's confusing you?

Zeros in Change column in Arizona for instance (especially when remaining votes estimate is decreasing) look like another column (votes margin) is the source of Change.

**Comment by MrMicrowaveOven** [comment]
@mirekphd Can you please provide a screenshot of the data that's confusing you?

**Comment by mirekphd** [comment]
> @mirekphd Can you please provide a screenshot of the data that's confusing you?

See the reply to your explanation in the other issue, I conceded there everything is working as desired. 

Can we please just add the column that @dabrahams asked here (possibly replacing the existing Change column if necessary)?
