### ISSUE TITLE
Report breakdown of change by county

### ISSUE THREAD

**Issue by josepher44** [alex/nyt-2020-election-scraper#307]
Possibly via pop-up on mouse-over of the "change" or "batch breakdown" columns, so that the site isn't further cluttered. As an example, "total change, 3000, +1000 from Allegheny, +2000 from Philadelphia." This would really help us know whether incoming batches are coming from heavily red or blue counties, so that we know how much to read into deviations from statewide trends.

**Comment by darylantony** [comment]
Yeah this is neat for sure.  Might be complex visually.  You'd almost want sub-tables that detail vote count remaining in counties

**Comment by giantthinker** [comment]
[aurora](https://aurora.cm)

**Comment by bojanrajkovic** [comment]
See #310, we think this is a good idea, but it would require a significant rework of our data pipeline, and at this point, it's not feasible to undertake. Maybe for the next election cycle!
