### ISSUE TITLE
Show the breakdown by county of remaining votes and the current trend percentage of each candidate in that county

### ISSUE THREAD

**Issue by 1972silver** [alex/nyt-2020-election-scraper#308]
I'm guessing this would be too much to do at this point, but would be very helpful for analysis of the outstanding vote.

Show the breakdown by county of remaining votes and the current trend percentage of each candidate in that county.

Thanks for the great work everyone!

**Comment by bojanrajkovic** [comment]
Yeah, doing any county-level breakdown would require us to significantly rework the data pipeline at this point. If we continue this for a future election cycle, we'll consider doing more with county-level data.
