### ISSUE TITLE
GA remaining votes look wrong

### ISSUE THREAD

**Issue by johnnymads-zz** [alex/nyt-2020-election-scraper#31]
I think the NYT pct is inaccurate. According to the GA sec of state site, there were 90,735 votes left to count at 1015pm 4 Nov. See:
https://sos.ga.gov/index.php/elections/with_90735_votes_out_officials_focused_on_getting_it_right

**Comment by alex** [comment]
Unfortunately we're just rendering GA data, not much we can do about this.

**Comment by alex** [comment]
Err, NYT data.

**Comment by alex** [comment]
We now note the origin of the data on the web version.
