### ISSUE TITLE
Add hyperlink to each flag pointing to official current election counts

### ISSUE THREAD

**Issue by codyro** [alex/nyt-2020-election-scraper#319]
Hyperlinking each flag to the official election sites for each state would be useful for people to check the local state election status directly.

`Alaska - https://www.elections.alaska.gov/results/20GENR/index.php`
`Arizona - https://results.arizona.vote/#/featured/18/0`
`Georgia - https://results.enr.clarityelections.com/GA/105369/web.264614/#/summary`
`Nevada - https://silverstateelection.nv.gov/USPresidential/#race1`
`North Carolina - https://www.ncsbe.gov/` 
`Pennsylvania - https://www.votespa.com/About-Elections/Pages/Counting-Dashboard.aspx`

**Comment by noobyogi0010** [comment]
Do we need this functionality?

**Comment by codyro** [comment]
> 
> 
> Do we need this functionality?

It's mostly due to the estimated remaining votes left and allows people to verify the numbers directly. _Need_ may be a stretch however.

**Comment by noobyogi0010** [comment]
@codyro I understand that. But these guys discuss among them and then mark some issues as an enhancement if necessary, so I was referring to that.

**Comment by bojanrajkovic** [comment]
We’ve considered linking to each state’s election website, but since we don’t use their data, we didn’t want to create any false equivalency. We also are wary of pushing any % of our traffic (which is fairly significant) to their websites, which are probably unprepared to deal with it.
