### ISSUE TITLE
Add iOS Home Screen Icon

### ISSUE THREAD

**Issue by bpmarkowitz** [alex/nyt-2020-election-scraper#321]
I would like to add a Home Screen icon. I have a PR ready to go with the icon file and proper tag added in the .tmpl file

![homescreen](https://user-images.githubusercontent.com/1587911/98442901-df375380-20d5-11eb-89bc-2faffe0b0dd7.jpg)

**Comment by bojanrajkovic** [comment]
👍, looks like a nice add! Go ahead and PR it!

**Comment by bpmarkowitz** [comment]
Thanks! Done
