### ISSUE TITLE
Text display in breakdown needs to be improved

### ISSUE THREAD

**Issue by Enivex** [alex/nyt-2020-election-scraper#324]
**Describe the bug**
Right now the trailing candidate's text is anchored go the start of their bar, so it disappears if they get a low proportion of the votes.

**Expected behavior**
Text needs to be right-justified

**Screenshots**
![Screenshot_20201107-160507_Firefox Beta](https://user-images.githubusercontent.com/2191754/98444739-a027f300-2113-11eb-9150-49b7763214c8.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S10+
 - OS: Android 10
 - Browser Firefox
 - Version Beta

**Comment by fractionalhare** [comment]
Thanks! We're working on this.

**Comment by Enivex** [comment]
It's not just the trailing candidate apparently. If the current leader gets few votes in a batch, their percentage gets cut off.

![Screenshot_20201107-162318_Firefox Beta](https://user-images.githubusercontent.com/2191754/98445040-bd5dc100-2115-11eb-97ca-53e30e94d95d.jpg)

**Comment by fractionalhare** [comment]
Yep, we have a change in motion to address that as well.

**Comment by titanous** [comment]
For now we've reverted in #334
