### ISSUE TITLE
Background color green when Timestamp < 5 min

### ISSUE THREAD

**Issue by centercirclesolutions** [alex/nyt-2020-election-scraper#325]
It's sometimes hard to see when new data arrives given the wall of data. This change would allow new rows to stand out amoung all the other older rows. Background color for only the Timestamp column would be sufficient

**Is your feature request related to any of these? We are not pursuing these at the moment.**

[X ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page
[ ] - changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**
No

**Clearly describe the solution you'd like**
Additional highlight to show when new data arrives

**Comment by titanous** [comment]
We note the updated states in the batch at the top of the page now. Between that, the ability to collapse the tables, and the complexity it would add to the live reloading, I think we'll leave things as-is.
