### ISSUE TITLE
Quick summary table at the top?

### ISSUE THREAD

**Issue by ijconlon** [alex/nyt-2020-election-scraper#328]
Not quite sure if this qualifies as "additional data" at the top of the page, but it would be helpful to have a single table at the top that just takes the _latest_ timestamp for each of the states and shows the associated figures. That way people only need to scroll down if they want to see a more complete trend.

Fantastic resource, regardless. Thanks to all who have contributed!

**Comment by titanous** [comment]
We already note states that were updated recently next to the batch timestamp. Between that and collapsed tables, I think that's all we're going to do.
