### ISSUE TITLE
Recount Threshold

### ISSUE THREAD

**Issue by blewe001** [alex/nyt-2020-election-scraper#329]
can you add state recount threshold and current margin.  e.g. PA has .50 threshold, current Biden lead is at.43.  Speculation is that the race will be called once the threshold is met.  this is the new metric we are all watching. 

*Is your feature request related to any of these? We are not pursuing these at the moment.**

[ ] - graphs and data visualizations
[ ] - projections and regression models
[ ] - additional data added to the top of the page
[ ] - changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**

**Comment by alex** [comment]
Closing as this is the same thing requested in #249, which we already declined.
