### ISSUE TITLE
Graphical Batch Breakdown drawing could be improved

### ISSUE THREAD

**Issue by superninjakiwi** [alex/nyt-2020-election-scraper#337]
**Describe the bug**

The graphical breakdown is super great, but has a few minor drawing errors when values skew very high or low. Left-side numbers draw underneath the right side color if the right side has a high percentage, and if the right side has a low percentage, the numbers move off the side of the box, potentially intersecting with other text.

**To Reproduce**
1. Go to https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html
2. Scroll down to Georgia(6/11/20 7:58 PM MST| High left value) or to North Carolina(6/11/20 4:26 PM MST| High right value)

**Expected behavior**
- Both left-side and right-side percentages should draw on top of both colors. 
- The right-side percentages should align to the right side of the box instead of the left side of the right-side color.

**Screenshots**
https://i.gyazo.com/4b279aac4beef194967350ce3c797c78.png
https://i.gyazo.com/d88f584ffdbae6a9374ccbf426eca755.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave (chromium derivative)
 - Version: Latest?

**Comment by titanous** [comment]
We've already reverted this in #334
