### ISSUE TITLE
Clearer total vote representation for each state

### ISSUE THREAD

**Issue by antifuchs** [alex/nyt-2020-election-scraper#339]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

- [x] graphs and data visualizations (arguably)

**Clearly describe the solution you'd like**

I would love if the top of the summary for each state had a less-unreadable representation of the total vote count: So far I've explained to two people that "leads with N votes, trails with M votes" means the total amount of votes they received, not the amount they're ahead/behind.

The batch breakdown has a nice percentage plot, it would be neat if each state's header had something like this too. I've mocked something up here:
![image](https://user-images.githubusercontent.com/11864/98446637-de5dec00-20ec-11eb-86dd-1674a3372fa3.png)

(corrected to represent ... more correct percentages)

**Comment by titanous** [comment]
We've added percentages to the header now. Thanks for the suggestion!
