### ISSUE TITLE
Last updated, Latest batch received in HTML version

### ISSUE THREAD

**Issue by russellrain** [alex/nyt-2020-election-scraper#34]
This is awesome!  How about a **Last updated**, **Latest batch received** on the top like on the text-only version of the report (so we can tell if there are new updates without scrolling the whole page)

**Comment by alex** [comment]
The text only version has those:

```

----------------------  --------------------------------------------------------------------------------
Last updated:           2020-11-05 15:07 UTC
Latest batch received:  2020-11-05 14:50 UTC
Prettier web version:   https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html
----------------------  --------------------------------------------------------------------------------
```

**Comment by russellrain** [comment]
ok, I was thinking it would be nice to have on the pretty version but I'll take whatever I can get :).  Thanks for sharing this

**Comment by russellrain** [comment]
> The text only version has those:
> 
> ```
> 
> ----------------------  --------------------------------------------------------------------------------
> Last updated:           2020-11-05 15:07 UTC
> Latest batch received:  2020-11-05 14:50 UTC
> Prettier web version:   https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html
> ----------------------  --------------------------------------------------------------------------------
> ```

ok, I was thinking it would be nice to have on the pretty version but I'll take whatever I can get :). Thanks for sharing this

**Comment by alex** [comment]
Oh, you're requesting these for the HTML version.

**Comment by titanous** [comment]
Last updated is in the title of the page.

**Comment by dain** [comment]
Can you add this to the page text? Chrome with tabs seems to truncates the page title.

**Comment by titanous** [comment]
On it.

**Comment by dain** [comment]
BTW I have no idea how hard this is, but it would be awesome if the time was rendered in my local TZ.

**Comment by acedriven** [comment]
A quick hack to deal w/ UTC / timezones would be to include time elapsed since last update / last batch received.

**Comment by dain** [comment]
Awesome! Thanks!
