### ISSUE TITLE
Visualize batch votes distribution and relate to hurdle

### ISSUE THREAD

**Issue by jkyro** [alex/nyt-2020-election-scraper#344]
- [x] graphs and data visualizations
- [ ] projections and regression models
- [ ] additional data added to the top of the page
- [ ] changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

I think it would be good to have a visual representation of the vote distribution and the hurdle, so that it would be easier to see whether the trailing candidate is actually catching up or not without parsing the numbers from different columns.

Something like this:
![Screenshot_20201107_200427](https://user-images.githubusercontent.com/11060369/98448476-f9ece500-2134-11eb-9b21-0fc62f1baeb4.png)

**Comment by titanous** [comment]
We've decided to leave the breakdown column as-is. Thanks for the suggestion though!
