### ISSUE TITLE
No issue - just a massive THANK YOU

### ISSUE THREAD

**Issue by natefox** [alex/nyt-2020-election-scraper#346]
Just wanted to say THANK YOU for this. This tool was my primary method of checking results cause it was so easy to know where things stood without loading giant, bloated news sites. I know there were many more like me that used this.

Thank you thank you thank you - to *everyone* who contributed!

@alex 
@frewsxcv 
@thomasdesr 
@fractionalhare 
@samczsun 
@titanous 
@bojanrajkovic 
@JulesDT 
@bellachp 
@saleemrashid 
...and the other 40 kind folks who made PRs and commits.

**Comment by Grocel** [comment]
Yeah it was a convenient tool.

Greetings from Germany. That race was `called(new President('Joe Biden'))` to the end.

**Comment by fancyham** [comment]
Yes, thank you!

**Comment by centercirclesolutions** [comment]
You guys did an excellent job! Thank you!

**Comment by luna-v1** [comment]
I wanted to do this same thing last night, but didnt want to mess with the construction process. Thank you guys, you did an amazing job with this one!

**Comment by witcephedrus** [comment]
I run a data/metrics shop at a big financial institution and have an appreciation for what you did. 
Awesome job. 
Thank you so much!

**Comment by tinatenatean** [comment]
It's a wonderful app!  Thanks so much for your work!

**Comment by fractionalhare** [comment]
We're thrilled it's been so useful to so many people!

**Comment by natefox** [comment]
Its _still_ useful. Until all the votes are in and certified, I'm keeping this open in a tab. Thank you again!
