### ISSUE TITLE
Support senate races

### ISSUE THREAD

**Issue by fancyham** [alex/nyt-2020-election-scraper#347]
**Is your feature request related to an issue? Please cite the issue.**

Senate races in NC and AK are expected to be very close!

**Clearly describe the solution you'd like**

Could you support results for the ongoing North Carolina and Alaska senate races, and the upcoming Georgia runoffs?

**Comment by titanous** [comment]
NC and AK are expected to come in one drop when they've finished counting, so there's not much point. GA is a couple months out. We'll see.
