### ISSUE TITLE
No Issue - even MORE thanks

### ISSUE THREAD

**Issue by podfeet** [alex/nyt-2020-election-scraper#359]
Everything about this project is awesome. It gave me all of the data to help me understand the progress throughout the days of anxiety (data calms me).  The fluidity with which it worked was awesome, from the expand/shrink tables to the auto-updating feature, and especially the way it allowed pinching out on mobile to see the entire table width.

Of course it being an open source project made it this great, but the real joy was when I came here to donate to thank you and instead you sent me to VotingWorks. Sent them $50 because of the work you did (and because, duh, voting.)

Thank you all for your work to make such an awesome tool for the world.

**Comment by tinatenatean** [comment]
I second what @NosillaCast says!  Thanks to everyone for your time and dedication building this invaluable app!  It really is wonderful.

**Comment by fractionalhare** [comment]
We're really glad it was a big help to you, and thank you so much for donating to a good cause.
