### ISSUE TITLE
Request: Add data for Maine's 2nd congressional district.

### ISSUE THREAD

**Issue by sxflynn** [alex/nyt-2020-election-scraper#361]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

- [ ] graphs and data visualizations
- [ ] projections and regression models
- [x ] additional data added to the top of the page
- [ ] changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

Is there any chance we could add data for Maine's 2nd congressional district? It remains to be called by many news orgs.

**Comment by titanous** [comment]
According to this, it's been called by almost everyone: https://www.nytimes.com/interactive/2020/11/03/upshot/network-race-call-tracker.html

We will be adding a new page that has all states on it.
