### ISSUE TITLE
Nationwide vote count

### ISSUE THREAD

**Issue by adrian-ye** [alex/nyt-2020-election-scraper#365]
Any way to see nationwide vote count similar to the state view? Curious because I am skeptical Trump gained >500k votes overnight. Thank you for all your hard work!

**Is your feature request related to any of these? We are not pursuing these at the moment.**

- [ ] graphs and data visualizations
- [ ] projections and regression models
- [ ] additional data added to the top of the page
- [ ] changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**

**Comment by fractionalhare** [comment]
Hey there. We discussed this possibility but we don't feel it's worthwhile for this project specifically. This particular statistic is pretty widely available from any of the other news outlets, and our focus is on historical data. We also don't want to encourage usecases that try to suss out fraudulent voting from one party or another - it's just not the intention of the project.
