### ISSUE TITLE
Not quite sure how this works, but I added all 50 states and DC

### ISSUE THREAD

**Issue by rezin8** [alex/nyt-2020-election-scraper#366]
**Is your feature request related to any of these? We are not pursuing these at the moment.**

- [ ] graphs and data visualizations
- [ ] projections and regression models
- [ ] additional data added to the top of the page
- [ ] changes to the hurdle rate. please see https://github.com/alex/nyt-2020-election-scraper/issues/194; the hurdle rate is not incorrect.

**Is your feature request related to an issue? Please cite the issue.**

**Clearly describe the solution you'd like**
Alex, I'm not quite sure how to do this, as I'm not really a programmer, I just dabble around in stuff. I went ahead and took your battleground states and rewrote that to include all the states information and dropped it in my fork of this repository. I didn't want to do a pull request because I'm not sure how to keep everything synced and didn't want to screw anything up if you merged my code with yours. But, if you want it, you can find it at: https://github.com/rezin8/nyt-2020-election-scraper

Thanks for doing this!

**Comment by fractionalhare** [comment]
Thanks for bringing this up! We've actually had this in development for a few days; you can see the [prep work](https://github.com/alex/nyt-2020-election-scraper/pull/351) that was started to add this feature. We hope to have it finished and launched soon.
