### ISSUE TITLE
Add in NC Senate / house races.

### ISSUE THREAD

**Issue by tatarize** [alex/nyt-2020-election-scraper#370]
The NC senate race might be interesting and worth adding. And the uncalled house races might be worth it. For example it might be worthwhile to know how the nail biter Garcia races in CA is going. And there's a few states with heavily democratic ballots that are going to start being counted in various house races.

**Comment by bojanrajkovic** [comment]
We've thought about state-level data, but it would require a complete rework of our data pipeline, which is heavily focused on presidential races right now.
