### ISSUE TITLE
North Carolina "Hurdle"

### ISSUE THREAD

**Issue by Jeoshua** [alex/nyt-2020-election-scraper#373]
According to the scraper information, there are approximately 188k votes remaining to count in NC, and a margin of 80k.
For some reason, the website is saying that 70% of votes must go toward Biden to close that gap.

Do some quick math... that's clearly wrong.

**Comment by sebsebmc** [comment]
We originally based our "Hurdle" calculation based on just splitting the estimated remaining votes between the 2 candidates but found there are a lot of improvements that can be made to be more accurate. I suggest checking out https://github.com/alex/nyt-2020-election-scraper/pull/367 and the other issues linked in there like #194 for details.
