### ISSUE TITLE
Batch Trend question -- not sure if a bug or I just don't understand :-) 

### ISSUE THREAD

**Issue by LiamKnuj2** [alex/nyt-2020-election-scraper#374]
Not sure I understand the math/data/APIs.  E.g., in AZ right now, Biden's margin is down to 14,000 votes. Trump's needs (Hurdle) 63.8% of the estimated 54k remaining ballots, to win. His moving average (Batch Trend) is 58.7% over the last 30,000 ballots counted. In the most recent (2 hours ago) Change of 6,252 votes, Trump got only 51.1%. So why does it show Trump's average (Batch Trend) **increasing** from 57.1% three hours ago to 58.7% two hours ago, when that two-hour (and biggest) Batch Breakdown shows his share **decreasing** to 51.1%? 

Thanks for your work! Very much appreciated! 

![github - Batch Trend 1a](https://user-images.githubusercontent.com/74225982/98627314-f054b000-22e1-11eb-85ba-92461534492f.jpg)

**Comment by sebsebmc** [comment]
The trend is based on the last 30,000 votes so you have to see what votes are getting dropped from the end. In this case there appears to be a very pro-Biden batch that is moving out of the 30k window. We dont have vote-by-vote data so we have to extrapolate a bit from the batch breakdowns.
