### ISSUE TITLE
Open Source the data scraper

### ISSUE THREAD

**Issue by Lucretiel** [alex/nyt-2020-election-scraper#375]
Unless I'm mistaken, there doesn't seem to be any code here that actually performs the data scraping and creates the commits; the existing code is only the site generator based on the scraped data. Would it be possible to open source the scraper itself?

**Comment by fractionalhare** [comment]
Everything is open sourced. The functionality you're looking for is implemented using a shell script executed as a recurring workflow by GitHub Actions. Look at [these files](https://github.com/alex/nyt-2020-election-scraper/tree/master/.github/workflows).

In particular: the original JSON dataset is grabbed from the [NYT source](https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/votes-remaining-page/national/president.json) using `curl` and parsed with `jq` before being written to `results.json`.
