### ISSUE TITLE
CSV Data's timestamps start at 2020-11-04 13:28:22.084000

### ISSUE THREAD

**Issue by dwootton** [alex/nyt-2020-election-scraper#385]
**Describe the bug**
When using the CSV data, the timestamp for many states begins at 2020-11-04 13:28:22.084000, which is ~13 hours after the data was first reported in some of them. 

**To Reproduce**
Go to all states csv and search for '2020-11-04 13:28:22.084000'

**Expected behavior**
I would expect that the data would begin right after 7 pm EST.

**Comment by titanous** [comment]
This is expected, as the scraper did not exist at 7pm, so the earliest timestamp you are seeing is from the first run of the scraper.
