### ISSUE TITLE
FYI, there's more election data available here...

### ISSUE THREAD

**Issue by d0ntw84f8** [alex/nyt-2020-election-scraper#390]
I love what you guys are doing here!  It inspired me to explore more NY Times data and scrape together other data types as well.  I've put what I dug up into [this repo](https://github.com/d0ntw84f8/election2020-timeseries-data), if you're interested.

There's county-level timeseries for the whole US, precinct-level timeseries for GA, FL, MI, NC, and PA (partial for the latter three), and state-level timeseries for senate and house races.  It's not as polished as what you have here, but the data is good and I think complementary to what you've done.

Thanks for all your hard work!

**Comment by thomasdesr** [comment]
Thanks! Glad to hear you enjoyed our project.
