### ISSUE TITLE
Limit rows per state

### ISSUE THREAD

**Issue by vecima** [alex/nyt-2020-election-scraper#40]
This is such an awesome resource.

Is there any way we could get the rows per state limited?  If not via a UI element, then maybe via URI params or something?

**Comment by shadowswan** [comment]
Maybe a drop down option?

**Comment by trouty-g** [comment]
$("tr").has(".timestamp").not(":contains('minutes')").not(":nth-child(-n+3)").remove();$("table").has("th:contains('Alaska')").remove();$("table").has("th:contains('North Carolina')").remove();

You can inject this in your browser's js console, or via tampermonkey.

**Comment by alex** [comment]
There's now a button for this.
