### ISSUE TITLE
Summary Table on top of page

### ISSUE THREAD

**Issue by amidongarrett** [alex/nyt-2020-election-scraper#46]
This is an awesome resource, thank you for putting it together. Is it possible to add a table to the top of the page with each state's most recent update?

**Comment by asielen** [comment]
I second this. 

I have been working around this by adding this css to the page. Maybe a switch can be added to toggle between the two. 

tr:not(:first-child) {display: none;}

It also removed the table headings but I have been staring a this page long enough to have those memorized.

**Comment by rentiak** [comment]
@asielen I think this will work to get headers? been a bit since I messed with it:
`tr:not(:first-child) td:not(:nth-child(0)){
    display: none;
}`

**Comment by jeffmikels** [comment]
My pull request has a modified python script to also generate a "compact" chart.

**Comment by schromick** [comment]
A 'last update' section - which state updated most recently, and how long ago, would be handy. Or a brief running list - a 'change log' of sorts...

**Comment by fractionalhare** [comment]
I am -1 on this. I think it's an idea with some merit, but at this point I don't think we should add any more visual complexity to the page.

**Comment by bojanrajkovic** [comment]
Agree with @fractionalhare, I don't think we want to make it visually any more complex at this time. We may revisit the UX at some point, but for now, the simplicity is a large part of the appeal.
