### ISSUE TITLE
Remaining votes for GA currently 47k

### ISSUE THREAD

**Issue by trouty-g** [alex/nyt-2020-election-scraper#47]
Not sure what's happening in the GA remining votes column, but this was just released in a presser from GA election officials.

**Comment by trouty-g** [comment]
Ah, just saw the closed issue. Carry on. Hopefully this gets sorted by NYT. My brain ticks seeing the hurdle @ 73%+

**Comment by alex** [comment]
Yeah, we rely on the NYT. Nothing we can do here.
