### ISSUE TITLE
NC oddities?

### ISSUE THREAD

**Issue by wagnerde** [alex/nyt-2020-election-scraper#52]
Perhaps not a coding issue at all, but does anyone have an explanation for the perfect 50.0% - 50.0% vote tallies for North Caroliona?  It seems unlikely that new votes would break so precisely and so consistently.  Also, some voting blocks have odd numbers of votes, but still 50.0% allocation to each candidate.  How is that possible?

<img width="1707" alt="Screen Shot 2020-11-05 at 1 22 10 PM" src="https://user-images.githubusercontent.com/38510695/98298065-40421880-1f6a-11eb-8cd1-16b00ace592f.png">

**Comment by alex** [comment]
I don't think we do, no. It's very hard to speculate without knowing more about the procedures that NC is using for counting.

**Comment by kuba-kubula** [comment]
Please note that the numbers of votes for both did not change. Only the remaining votes (est.) changed. (To me looks like they removed some non-valid votes/mails and did not post updated figures of already-processed votes)

**Comment by wagnerde** [comment]
I'm just puzzled why the vote differential did not wobble even a single vote (up or down) when new blocks with odd numbers are split ~50-50?

**Comment by dd36** [comment]
Block Breakdown calculation probably needs a few more conditions.

**Comment by dd36** [comment]
Best guess is: they need to "N/A" Block Breakdown when there are decreases in Vote Remaining not just increases. 

Is Change only paying attention to Votes Remaining and not a diff on totals counted? That should also be adjusted.

I am just making educated guesses.

**Comment by wagnerde** [comment]
Got it.  If these updates are not new votes being added, but instead alterations to the estimated # of votes remaining, then the breakdowns now make sense.  It was not clear from these tables that the total # votes counted had not changed.
