### ISSUE TITLE
Negative Percent Block Breakdown

### ISSUE THREAD

**Issue by mftruso** [alex/nyt-2020-election-scraper#56]
PA at `2020-11-05 02:26:44 UTC` gives block breakdown as `Trump -4.3% / 104.3% Biden`. Shouldn't be able to get more than 100% of the votes in a time period?

<img width="1349" alt="Screen Shot 2020-11-05 at 3 40 15 PM" src="https://user-images.githubusercontent.com/5644190/98303294-7f309800-1f83-11eb-8186-e1cde30e91d7.png">

**Comment by frewsxcv** [comment]
answered it on twitter: https://twitter.com/frewsxcv/status/1324468252618203136
