### ISSUE TITLE
Make an easy-to-manipulate version of the tables for easier data visualization

### ISSUE THREAD

**Issue by hitchbro** [alex/nyt-2020-election-scraper#64]
I think it'd be great if we could see running totals based on the current candidate's percentage from the latest blocks- I tried to do this but ended up finding difficulty in the iterative nature of the actual output HTMLs.

**Comment by thomasdesr** [comment]
Thanks for reaching out @hitchbro!

#83  added a `.csv` file we're including in our output that folks are using to do fun visualization things :D

Give it a look and let us know if there is something missing :D
