### ISSUE TITLE
In summary at top, show current leader and indicate current predicted winner

### ISSUE THREAD

**Issue by fancyham** [alex/nyt-2020-election-scraper#68]
Thanks for making this!

Although it's not accurate, I think all of us are trying to figure out where the states are going to end up, and by how much margin.

So suggest something like this:

Arizona: Biden leads with 1,000,000 votes.  Current trend with 10,000 votes remaining will have Trump winning by 300 votes.

**Comment by alex** [comment]
This is too far into the projection space for my comfort. Our goal is to inform on what the data is, not make projections.
