### ISSUE TITLE
Filter out older blocks

### ISSUE THREAD

**Issue by schromick** [alex/nyt-2020-election-scraper#82]
Filter out blocks over selectable amount of time - for example, older than 1 hour, 5 hours, 1 day

**Comment by WarrenBuffering** [comment]
What if the tables were collapsible?

**Comment by fsmontenegro** [comment]
The collapsible tables help within a state. Right now, for example, Alaska is dead quiet (last update a day ago) but taking up prime screen real estate, so it'd be great to filter out any update older than, say 1-2 hours.

**Comment by bojanrajkovic** [comment]
This is largely obviated by shrinking tables. We don't want to drop any states that are still in the hunt, even if their updates are old (AZ, NV, etc.).
