### ISSUE TITLE
NC vote differential doesn't seem to update

### ISSUE THREAD

**Issue by olivierlacan** [alex/nyt-2020-election-scraper#85]
Despite changes that can't possibly be 50/50 splits between candidates. Is this a known issue? 

<img width="1437" alt="Screen Shot 2020-11-05 at 20 11 23" src="https://user-images.githubusercontent.com/65950/98314146-62a45800-1fa3-11eb-9546-70e01976a835.png">

**Comment by calvinkarpenko** [comment]
The code only displays 1 decimal place, so it looks like it is a 0.0x% and so it's rounded.

**Comment by olivierlacan** [comment]
I'm talking about the `Vote Differential` which is not a decimal number.

**Comment by sebsebmc** [comment]
What is happening is that the underlying data source has revised their estimate of how many ballots are remaining downwards
