### ISSUE TITLE
Prune Change=0 in Shrink Tables mode

### ISSUE THREAD

**Issue by dain** [alex/nyt-2020-election-scraper#91]
For the `Shrink Tables` mode, I would hide blocks with no votes.  Alternative, the blocks with zero votes don't seem particularly useful, so I would consider hiding them entirely.

**Comment by gravitypersists** [comment]
why are there blocks with 0 votes in the first place? is that the underlying bug?

**Comment by mr-ransel** [comment]
It looks like the blocks with 0 votes are actually a manifestation of the varying/updating NYT "Votes Remaining" estimate, which will affect the calculated Hurdle % in the final column

**Comment by frewsxcv** [comment]
this was fixed in https://github.com/alex/nyt-2020-election-scraper/pull/107
